import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Split Fee Agreements Explained | RecXchange",
  description: "What to include in a split fee agreement, why they matter, and how to protect yourself before sharing candidates. Practical guide for recruiters.",
  keywords: [
    "split fee agreement",
    "split fee agreement template",
    "split fee recruitment agreement",
    "recruiter split fee contract",
    "split placement agreement",
    "split fee terms",
    "recruitment fee sharing agreement",
    "split fee agreement UK"
  ],
  alternates: { canonical: "https://recxchange.io/blog/split-fee-agreement-guide" },
  openGraph: {
    title: "Split Fee Agreements: What to Include",
    description: "What to include in a split fee agreement, why they matter, and how to protect yourself before sharing candidates.",
    url: "https://recxchange.io/blog/split-fee-agreement-guide",
    type: "article",
    images: [{ url: "https://haaqtnq6favvrbuh.public.blob.vercel-storage.com/REX-Icon-GW-Small-25.png", width: 1200, height: 630, alt: "Split Fee Agreements Explained" }]
  },
  twitter: { card: "summary_large_image", title: "Split Fee Agreements: What to Include", description: "What to include in a split fee agreement and how to protect yourself before sharing candidates.", images: ["https://haaqtnq6favvrbuh.public.blob.vercel-storage.com/REX-Icon-GW-Small-25.png"], creator: "@RecXchange" }
};

export default function SplitFeeAgreementGuidePage() {
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": "https://recxchange.io/blog/split-fee-agreement-guide#article",
    "url": "https://recxchange.io/blog/split-fee-agreement-guide",
    "headline": "Split Fee Agreements: What to Include",
    "description": "What to include in a split fee agreement, why they matter, and how to protect yourself before sharing candidates.",
    "author": { "@type": "Person", "name": "Tom Andrews", "jobTitle": "CEO and Co-Founder", "url": "https://recxchange.io", "worksFor": { "@type": "Organization", "name": "RecXchange" } },
    "publisher": { "@type": "Organization", "name": "RecXchange", "logo": { "@type": "ImageObject", "url": "https://haaqtnq6favvrbuh.public.blob.vercel-storage.com/REX-Icon-GW-Small-25.png" } },
    "datePublished": "2026-04-02",
    "dateModified": "2026-04-02",
    "mainEntityOfPage": { "@type": "WebPage", "@id": "https://recxchange.io/blog/split-fee-agreement-guide" },
    "isPartOf": { "@id": "https://recxchange.io/#website" },
    "breadcrumb": {
      "@type": "BreadcrumbList",
      "itemListElement": [
        { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://recxchange.io" },
        { "@type": "ListItem", "position": 2, "name": "Blog", "item": "https://recxchange.io/blog" },
        { "@type": "ListItem", "position": 3, "name": "Split Fee Agreements Explained", "item": "https://recxchange.io/blog/split-fee-agreement-guide" }
      ]
    }
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What should a split fee agreement include?",
        "acceptedAnswer": { "@type": "Answer", "text": "A split fee agreement should include the fee split percentage, payment terms and timelines, candidate ownership definitions, an exclusivity period, a deal expiry clause, and a dispute resolution process. Both parties should sign before any candidate data is shared." }
      },
      {
        "@type": "Question",
        "name": "When should I sign a split fee agreement?",
        "acceptedAnswer": { "@type": "Answer", "text": "You should sign a split fee agreement before sharing any candidate information whatsoever. This means before sending a CV, a name, a LinkedIn profile, or even a verbal description that could identify the candidate. Once the other party has the candidate's details, your leverage disappears entirely." }
      },
      {
        "@type": "Question",
        "name": "Are split fee agreements legally binding?",
        "acceptedAnswer": { "@type": "Answer", "text": "Yes. A split fee agreement is a legally binding contract in the UK, provided it contains clear terms, is signed by both parties, and involves an exchange of value (the candidate introduction in return for a share of the placement fee). Digital signatures and timestamped platform agreements, such as those generated by RecXchange, are fully enforceable." }
      }
    ]
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <main className="relative bg-[#0a0a0f] min-h-screen">
        <div className="max-w-3xl mx-auto px-6 py-24">
          <p className="text-cyan-400 text-sm font-bold uppercase tracking-widest mb-4">Guide</p>
          <h1 className="text-4xl md:text-5xl font-black text-white mb-6">Split Fee Agreements Explained</h1>
          <p className="text-gray-400 text-sm mb-10">Published: April 2026 &nbsp;·&nbsp; 8 min read</p>

          <p className="text-gray-300 text-lg mb-8 leading-relaxed">
            Every recruiter who has worked splits has a version of the same story. You share a candidate in good faith with another agency. The candidate gets placed. Then the other recruiter ghosts you, claims they already had the candidate on file, or quietly pockets the full fee. No agreement was signed. You have no proof of the introduction. You are left with nothing. This is exactly why split fee agreements exist, and why you should never collaborate without one.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">What Is a Split Fee Agreement?</h2>
          <p className="text-gray-300 mb-6 leading-relaxed">
            A split fee agreement is a written contract between two recruitment parties that sets out how a placement fee will be divided when they collaborate on filling a role. It defines who introduced the candidate, who holds the job, what percentage each party receives, and what happens if something goes wrong. Think of it as the terms of business between two recruiters rather than between a recruiter and a client. Without one, you are relying entirely on trust. In recruitment, that is not a strategy.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">What Every Agreement Should Include</h2>
          <p className="text-gray-300 mb-4 leading-relaxed">
            A proper split fee agreement does not need to be fifty pages long, but it does need to cover six core areas. Miss any of these and you are leaving gaps that will cost you.
          </p>
          <ul className="text-gray-300 mb-6 space-y-2 list-none">
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Fee split percentage.</strong> The exact ratio each party receives. State it clearly: 50/50, 60/40, or 70/30. No ambiguity.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Payment terms.</strong> When each party gets paid, how payment is triggered, and what happens if the client pays late. Specify whether the role-holder pays the candidate-holder directly or whether payment flows through a platform.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Candidate ownership.</strong> A clear definition of who introduced the candidate and how that introduction is recorded. This is the single biggest source of disputes in split fee arrangements.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Exclusivity period.</strong> How long the candidate-holder has exclusive rights to that candidate for the specific role. Without this, the role-holder could wait out the collaboration and approach the candidate directly later.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Deal expiry.</strong> A defined window after which the agreement lapses if no placement is made. Typically 6 to 12 months. This protects both sides from indefinite obligations.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Dispute resolution.</strong> A process for handling disagreements. Mediation, arbitration, or a named jurisdiction. Without this, your only option is litigation, which is slow, expensive, and rarely worth it for a single placement fee.</span></li>
          </ul>

          <h2 className="text-2xl font-bold text-white mb-4">Common Split Fee Percentages</h2>
          <p className="text-gray-300 mb-4 leading-relaxed">
            There is no single correct split. The right percentage depends on who is contributing what to the placement.
          </p>
          <ul className="text-gray-300 mb-6 space-y-2 list-none">
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">50/50</strong> is the industry standard. Both parties contribute roughly equally: one holds the role, the other holds the candidate. Simple, fair, and the most widely used arrangement in the UK.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">60/40</strong> typically favours the role-holder, recognising that maintaining the client relationship, managing the process, and handling invoicing carries more ongoing work. Some arrangements flip this to favour the candidate-holder if the candidate is particularly hard to find.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">70/30</strong> is common on platforms like RecXchange's RecX Direct product, where the candidate-holder takes 70% of the total fee. This reflects the fact that the candidate is the scarce asset. Finding a good client is hard. Finding the right candidate is harder.</span></li>
          </ul>

          <h2 className="text-2xl font-bold text-white mb-4">When Should the Agreement Be Signed?</h2>
          <p className="text-gray-300 mb-6 leading-relaxed">
            Before any candidate data is shared. Full stop. Not after the first interview. Not once the client shows interest. Before you send a CV, a name, a LinkedIn URL, or even a verbal description that could identify the candidate. The moment the other party knows who your candidate is, your leverage is gone. If they decide not to honour the split, you have no contractual protection and no practical way to enforce your claim. Signing the agreement first is not being difficult. It is being professional. Any recruiter who pushes back on this is telling you something about how they operate.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">How RecXchange Handles Agreements</h2>
          <p className="text-gray-300 mb-6 leading-relaxed">
            On RecXchange, split fee agreements are generated automatically when a candidate-holding recruiter expresses interest in a role. The agreement is timestamped, records both parties, defines the fee split, and locks in candidate ownership before any candidate details are visible to the role-holder. There is no manual paperwork, no chasing signatures, and no grey areas. The agreement is digitally signed within the platform and is legally binding under UK contract law. Payment terms are enforced through the platform, so there is no risk of one party withholding the other's share. This is the way split fee recruitment should always have worked.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">Red Flags to Watch For</h2>
          <p className="text-gray-300 mb-4 leading-relaxed">
            If you are collaborating on splits outside a platform, watch for these warning signs.
          </p>
          <ul className="text-gray-300 mb-6 space-y-2 list-none">
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">No written agreement.</strong> If the other recruiter wants to work on a handshake, walk away. Verbal agreements are almost impossible to enforce and rarely survive a dispute.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Vague terms.</strong> Phrases like "we'll sort out the split later" or "roughly 50/50" are not terms. They are invitations to be taken advantage of. Every number and every deadline should be explicit.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Pressure to share first.</strong> If someone is pushing you to send the CV before the agreement is signed, ask yourself why. A recruiter who genuinely intends to honour the split has no reason to resist signing first.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">No candidate ownership clause.</strong> Without a clear record of who introduced whom, disputes become a matter of one person's word against another's. Insist on a timestamped introduction record.</span></li>
            <li className="flex items-start gap-3"><span className="text-cyan-400 mt-1">→</span><span><strong className="text-white">Resistance to platform use.</strong> Recruiters who refuse to use a platform that enforces agreements and tracks introductions are often the ones who benefit from the lack of transparency.</span></li>
          </ul>

          <div className="mt-10 mb-8 p-5 rounded-2xl border border-white/10 bg-white/[0.02] flex flex-col sm:flex-row gap-4 items-start">
            <div className="w-12 h-12 rounded-full bg-cyan-500/10 border border-cyan-400/20 flex items-center justify-center text-cyan-400 font-bold text-lg flex-shrink-0">TA</div>
            <div>
              <p className="text-white font-bold text-sm mb-1">Tom Andrews</p>
              <p className="text-gray-400 text-xs mb-2">CEO and Co-Founder, RecXchange</p>
              <p className="text-gray-500 text-xs leading-relaxed">Tom has spent over 14 years in specialist recruitment across building materials, industrial engineering, M&amp;E, and mental health sectors. He co-founded RecXchange to give independent and specialist recruiters a better way to collaborate, split fees, and make more placements without the politics of traditional agency networks.</p>
            </div>
          </div>

          <div className="mt-12 p-6 rounded-2xl border border-cyan-400/20 bg-cyan-400/5">
            <p className="text-cyan-400 font-bold mb-2">Protect every split placement automatically.</p>
            <p className="text-gray-300 text-sm">Join RecXchange and get auto-generated, legally binding split fee agreements on every collaboration. No paperwork, no chasing signatures, no risk of getting cut out.</p>
          </div>
        </div>
      </main>
    </>
  );
}
