import { NextResponse } from 'next/server';

interface Role {
  id: string;
  source: 'recx_direct' | 'xchange';
  title: string;
  descriptionSnippet: string;
  company: string;
  location: string;
  workModel: 'remote' | 'hybrid' | 'onsite';
  industry: string;
  seniorityLevel: string;
  salaryMin: number;
  salaryMax: number;
  salaryCurrency: string;
  roleType: string;
  postedAt: string;
  splitAmount?: number;
  splitCurrency?: string;
}

interface APIResponse {
  total: number;
  lastUpdated: string;
  roles: Role[];
}

const CURRENCY_RATES: Record<string, number> = {
  'USD': 1, 'GBP': 1.27, 'EUR': 1.09, 'CAD': 0.72,
  'AUD': 0.66, 'SGD': 0.75, 'AED': 0.27, 'INR': 0.012, 'ZAR': 0.055,
};

function convertToUSD(amount: number, currency: string): number {
  return amount * (CURRENCY_RATES[currency] || 1);
}

// ─── BATCH 1: Roles 1–42 ────────────────────────────────────────────────────
const ROLES_BATCH_1: Role[] = [
  { id: 'r-001', source: 'recx_direct', title: 'Maintenance Manager', descriptionSnippet: 'Experienced Maintenance Manager required for a busy industrial facility in Ponca City, OK. You will oversee preventive and reactive maintenance programmes, lead a team of technicians, and ensure plant reliability and compliance with H&S standards.', company: 'RecX Direct Client', location: 'Ponca City, OK, USA', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 70000, salaryMax: 90000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-01T09:00:00.000Z', splitAmount: 9500, splitCurrency: 'USD' },
  { id: 'r-002', source: 'recx_direct', title: 'Financial Controller', descriptionSnippet: 'A growing business in Gouverneur, NY is seeking a Financial Controller to lead all financial reporting, budgeting, and cash flow management. CPA preferred with experience in manufacturing or professional services environments.', company: 'RecX Direct Client', location: 'Gouverneur, NY, USA', workModel: 'hybrid', industry: 'Finance & Accounting', seniorityLevel: 'senior', salaryMin: 90000, salaryMax: 120000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-02T09:00:00.000Z', splitAmount: 8500, splitCurrency: 'USD' },
  { id: 'r-003', source: 'xchange', title: 'Controls Engineer', descriptionSnippet: 'Controls Engineer required for a fast-paced automation project in Orlando, FL. You will design, programme and commission PLC/SCADA systems, and work closely with mechanical and electrical teams on complex industrial automation builds.', company: 'Xchange Partner', location: 'Orlando, FL, USA', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 80000, salaryMax: 110000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-02T10:00:00.000Z', splitAmount: 8500, splitCurrency: 'USD' },
  { id: 'r-004', source: 'recx_direct', title: 'ADHD Nurse / Specialist Prescriber', descriptionSnippet: 'A well-established mental health service in the UK is seeking an experienced ADHD Nurse with prescribing qualifications. You will conduct ADHD assessments, manage caseloads, and prescribe medication under agreed clinical frameworks.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'senior', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T09:00:00.000Z', splitAmount: 4000, splitCurrency: 'USD' },
  { id: 'r-005', source: 'recx_direct', title: 'Sales Consultant', descriptionSnippet: 'A dynamic sales team in Nottingham, UK is looking for a motivated Sales Consultant to manage an existing account base and drive new business. Strong track record in B2B consultative sales required.', company: 'RecX Direct Client', location: 'Nottingham, UK', workModel: 'hybrid', industry: 'Sales', seniorityLevel: 'mid', salaryMin: 25000, salaryMax: 35000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T10:00:00.000Z', splitAmount: 2500, splitCurrency: 'USD' },
  { id: 'r-006', source: 'recx_direct', title: 'Associate Mechanical Engineer - Science, Research & Mission Critical', descriptionSnippet: 'A leading MEP consultancy in London is seeking an Associate Mechanical Engineer specialising in science, research and mission-critical facilities. You will lead mechanical design on high-profile laboratory and data centre projects.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T09:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
  { id: 'r-007', source: 'recx_direct', title: 'Business Development Manager', descriptionSnippet: 'A high-growth B2B company is hiring an experienced Business Development Manager to cover Florida, Georgia, or Texas. You will drive new logo acquisition, manage complex sales cycles, and build long-term client partnerships.', company: 'RecX Direct Client', location: 'Florida / Georgia / Texas, USA', workModel: 'remote', industry: 'Sales', seniorityLevel: 'senior', salaryMin: 100000, salaryMax: 140000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-04T10:00:00.000Z', splitAmount: 15000, splitCurrency: 'USD' },
  { id: 'r-008', source: 'recx_direct', title: 'Homecare Nurse - Oncology', descriptionSnippet: 'An oncology homecare provider in South Wales is recruiting an experienced Nurse to deliver chemotherapy and supportive care to patients in their own homes. NMC registration and oncology experience essential.', company: 'RecX Direct Client', location: 'South Wales, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 34000, salaryMax: 42000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T11:00:00.000Z', splitAmount: 2500, splitCurrency: 'USD' },
  { id: 'r-009', source: 'recx_direct', title: 'Clinic Nurse - Oncology', descriptionSnippet: 'A busy oncology clinic in Stoke-on-Trent is looking for an experienced Clinic Nurse to administer systemic anti-cancer therapies (SACT) and provide holistic care to cancer patients attending for treatment.', company: 'RecX Direct Client', location: 'Stoke-on-Trent, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 34000, salaryMax: 42000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T09:00:00.000Z', splitAmount: 2500, splitCurrency: 'USD' },
  { id: 'r-010', source: 'recx_direct', title: 'Senior Electrical Engineer', descriptionSnippet: 'A major engineering consultancy in Edinburgh is seeking a Senior Electrical Engineer to deliver high-quality electrical designs across commercial, residential and infrastructure projects. Chartered or working towards chartership preferred.', company: 'RecX Direct Client', location: 'Edinburgh, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T10:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-011', source: 'recx_direct', title: 'Senior Electrical Engineer', descriptionSnippet: 'A leading building services consultancy in Glasgow requires a Senior Electrical Engineer with strong M&E background across commercial and industrial sectors. Experience with BIM and AutoCAD is advantageous.', company: 'RecX Direct Client', location: 'Glasgow, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T11:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-012', source: 'xchange', title: 'Software Engineering Expert', descriptionSnippet: 'A US-based technology company is seeking a highly experienced Software Engineering Expert to drive technical strategy, mentor engineering teams, and architect scalable solutions. Full-stack expertise with cloud-native systems required.', company: 'Xchange Partner', location: 'USA (Remote)', workModel: 'remote', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 150000, salaryMax: 200000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-05T12:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-013', source: 'xchange', title: 'Technical Support & Customer Success Professional', descriptionSnippet: 'A growing SaaS business operating in Nigeria is looking for a technically-minded Customer Success professional to onboard clients, troubleshoot product issues and drive retention. Strong communication and technical aptitude required.', company: 'Xchange Partner', location: 'Nigeria (Remote)', workModel: 'remote', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 20000, salaryMax: 35000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-06T09:00:00.000Z', splitAmount: 3500, splitCurrency: 'GBP' },
  { id: 'r-014', source: 'xchange', title: 'Technical Content Writer', descriptionSnippet: 'A technology company in California is hiring a Technical Content Writer to produce developer documentation, API guides, blog posts and product tutorials. Strong technical writing background and ability to simplify complex concepts essential.', company: 'Xchange Partner', location: 'California, USA', workModel: 'remote', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 80000, salaryMax: 110000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-06T10:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-015', source: 'xchange', title: 'Retail Operations Manager', descriptionSnippet: 'A US-based retail group is seeking a Retail Operations Manager to oversee multi-site operations, drive performance standards, and manage a team of store managers. Strong multi-site retail leadership background required.', company: 'Xchange Partner', location: 'USA', workModel: 'onsite', industry: 'Retail & Consumer', seniorityLevel: 'senior', salaryMin: 80000, salaryMax: 100000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-06T11:00:00.000Z', splitAmount: 3000, splitCurrency: 'USD' },
  { id: 'r-016', source: 'xchange', title: 'Clinical Data Expert - Clinical Trial Matching Project', descriptionSnippet: 'A US-based healthcare technology company is recruiting a Clinical Data Expert to support a clinical trial matching project. You will work with complex patient datasets, eligibility criteria, and clinical data pipelines. US-based candidates only.', company: 'Xchange Partner', location: 'USA (Remote)', workModel: 'remote', industry: 'Healthcare & Nursing', seniorityLevel: 'senior', salaryMin: 90000, salaryMax: 130000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-06T12:00:00.000Z', splitAmount: 3000, splitCurrency: 'USD' },
  { id: 'r-017', source: 'xchange', title: 'Credit Controller - Nordic Speaking', descriptionSnippet: 'A financial services business in London is recruiting a Nordic-speaking Credit Controller to manage accounts across Scandinavian markets. Strong credit control experience and fluency in Swedish, Norwegian or Danish required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Finance & Accounting', seniorityLevel: 'mid', salaryMin: 30000, salaryMax: 40000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T09:00:00.000Z', splitAmount: 1200, splitCurrency: 'GBP' },
  { id: 'r-018', source: 'xchange', title: 'Health & Safety Manager', descriptionSnippet: 'A large industrial organisation in Melbourne, Australia is seeking an experienced Health & Safety Manager to develop and implement H&S management systems, lead incident investigations, and drive a safety-first culture across multiple sites.', company: 'Xchange Partner', location: 'Melbourne, Australia', workModel: 'onsite', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 180000, salaryMax: 220000, salaryCurrency: 'AUD', roleType: 'permanent', postedAt: '2026-03-07T10:00:00.000Z', splitAmount: 16500, splitCurrency: 'AUD' },
  { id: 'r-019', source: 'xchange', title: 'Mechanical Fitter / Welder', descriptionSnippet: 'A UK engineering business is seeking a skilled Mechanical Fitter / Welder with experience in fabrication and installation. You will work across a range of industrial projects requiring precision fitting, welding and assembly skills.', company: 'Xchange Partner', location: 'United Kingdom', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T11:00:00.000Z', splitAmount: 4320, splitCurrency: 'GBP' },
  { id: 'r-020', source: 'xchange', title: 'SHEQ Advisor', descriptionSnippet: 'A UK-based contractor is hiring a SHEQ Advisor to support safety, health, environment and quality compliance across active project sites. NEBOSH qualified with experience in construction or industrial environments required.', company: 'Xchange Partner', location: 'United Kingdom', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 40000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T12:00:00.000Z', splitAmount: 3600, splitCurrency: 'GBP' },
  { id: 'r-021', source: 'recx_direct', title: 'Psychiatric Nurse Practitioner', descriptionSnippet: 'A private mental health clinic in London is seeking a Psychiatric Nurse Practitioner to assess, diagnose and treat adults with complex mental health needs. NMP qualification and relevant clinical experience required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 75000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-01T08:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
  { id: 'r-022', source: 'recx_direct', title: 'Site Manager - Commercial Construction', descriptionSnippet: 'A main contractor in the North West of England is seeking an experienced Site Manager to oversee a commercial construction project from groundworks to handover. SMSTS, First Aid, and CSCS gold card required.', company: 'RecX Direct Client', location: 'Manchester, UK', workModel: 'onsite', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-02T08:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
  { id: 'r-023', source: 'xchange', title: 'Principal AI Engineer', descriptionSnippet: 'Leading AI/ML team building next-generation recommendation systems. Python, TensorFlow, distributed systems experience required. Strong background in deep learning and NLP.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 120000, salaryMax: 160000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-20T09:00:00.000Z', splitAmount: 14000, splitCurrency: 'GBP' },
  { id: 'r-024', source: 'recx_direct', title: 'Talent Acquisition Partner', descriptionSnippet: 'A fast-scaling technology company in New York is hiring an experienced Talent Acquisition Partner to own end-to-end recruitment for technical roles. Strong stakeholder management and direct sourcing skills required.', company: 'RecX Direct Client', location: 'New York, USA', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'mid', salaryMin: 90000, salaryMax: 120000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-01T11:00:00.000Z', splitAmount: 9500, splitCurrency: 'USD' },
  { id: 'r-025', source: 'recx_direct', title: 'Structural Engineer', descriptionSnippet: 'A multi-disciplinary engineering consultancy in Birmingham is seeking a Structural Engineer to work on a diverse portfolio of residential, commercial and infrastructure projects. IStructE membership preferred.', company: 'RecX Direct Client', location: 'Birmingham, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 40000, salaryMax: 58000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T09:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-026', source: 'xchange', title: 'Head of Talent Acquisition', descriptionSnippet: 'Strategic TA leader to build and scale talent function for high-growth fintech. Experience building teams from 100-500+. Strong employer branding and analytics focus.', company: 'Xchange Partner', location: 'New York, USA', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'executive', salaryMin: 150000, salaryMax: 200000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-18T14:00:00.000Z', splitAmount: 18000, splitCurrency: 'USD' },
  { id: 'r-027', source: 'recx_direct', title: 'Regional Sales Manager - Industrial', descriptionSnippet: 'A leading supplier of industrial equipment is seeking a Regional Sales Manager to grow revenue across the Midlands and North of England. Field-based with a strong track record in B2B industrial or technical sales.', company: 'RecX Direct Client', location: 'Midlands / North England, UK', workModel: 'remote', industry: 'Sales', seniorityLevel: 'senior', salaryMin: 50000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T10:00:00.000Z', splitAmount: 7500, splitCurrency: 'USD' },
  { id: 'r-028', source: 'recx_direct', title: 'Community Mental Health Nurse', descriptionSnippet: 'A community mental health team in the East Midlands is seeking an experienced CMHN to manage a caseload of adults with serious mental illness. RMN qualified with strong knowledge of CPA and risk assessment.', company: 'RecX Direct Client', location: 'East Midlands, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 48000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T11:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-029', source: 'xchange', title: 'Quantitative Researcher', descriptionSnippet: 'Systematic trading firm seeking quant researcher for alpha generation. Strong C++/Python, statistical modelling, and financial markets knowledge. PhD preferred.', company: 'Xchange Partner', location: 'Singapore', workModel: 'onsite', industry: 'Finance & Accounting', seniorityLevel: 'senior', salaryMin: 180000, salaryMax: 250000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-22T10:00:00.000Z', splitAmount: 25000, splitCurrency: 'USD' },
  { id: 'r-030', source: 'recx_direct', title: 'Electrical Project Manager', descriptionSnippet: 'A national M&E contractor is seeking an Electrical Project Manager to deliver high-value commercial and industrial projects across the UK. You will oversee design, procurement, installation and commissioning with full P&L accountability.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 60000, salaryMax: 80000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T09:00:00.000Z', splitAmount: 8000, splitCurrency: 'USD' },
  { id: 'r-031', source: 'xchange', title: 'Marketing Director - B2B SaaS', descriptionSnippet: 'Growth marketing leader for B2B SaaS scale-up. Full-funnel expertise, team building, performance marketing, and brand strategy. 7+ years experience required.', company: 'Xchange Partner', location: 'Berlin, Germany', workModel: 'hybrid', industry: 'Marketing', seniorityLevel: 'senior', salaryMin: 100000, salaryMax: 140000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-21T08:00:00.000Z', splitAmount: 15000, splitCurrency: 'EUR' },
  { id: 'r-032', source: 'recx_direct', title: 'Building Services Engineer - M&E', descriptionSnippet: 'A building services consultancy in London seeks a Building Services Engineer with strong M&E design experience across commercial fit-out and new build projects. AutoCAD and Revit MEP proficiency required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T10:00:00.000Z', splitAmount: 6000, splitCurrency: 'USD' },
  { id: 'r-033', source: 'recx_direct', title: 'Registered General Nurse - ICU', descriptionSnippet: 'A leading private hospital in Dubai is seeking an experienced ICU Nurse with at least 2 years of critical care experience. DHA or MOH licence preferred. Tax-free salary and accommodation allowance on offer.', company: 'RecX Direct Client', location: 'Dubai, UAE', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 60000, salaryMax: 80000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-03-09T11:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
  { id: 'r-034', source: 'xchange', title: 'Cloud Solutions Architect', descriptionSnippet: 'Enterprise cloud architect for digital transformation projects. Azure specialist, architecture patterns, security, and client-facing experience required.', company: 'Xchange Partner', location: 'Austin, TX, USA', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 140000, salaryMax: 180000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-17T13:00:00.000Z', splitAmount: 16000, splitCurrency: 'USD' },
  { id: 'r-035', source: 'recx_direct', title: 'HR Business Partner', descriptionSnippet: 'A UK-wide professional services firm is seeking an experienced HR Business Partner to support senior stakeholders on all people matters, including ER, talent management, org design and change programmes.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 75000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T09:00:00.000Z', splitAmount: 8000, splitCurrency: 'USD' },
  { id: 'r-036', source: 'xchange', title: 'Senior DevOps Engineer', descriptionSnippet: 'Cloud-native DevOps expert to lead infrastructure automation. AWS/GCP, Kubernetes, Terraform, CI/CD pipelines. Building highly scalable systems.', company: 'Xchange Partner', location: 'Remote (Global)', workModel: 'remote', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 90000, salaryMax: 130000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-19T11:00:00.000Z', splitAmount: 11000, splitCurrency: 'GBP' },
  { id: 'r-037', source: 'recx_direct', title: 'Operations Director - Logistics', descriptionSnippet: 'A national logistics business is seeking an Operations Director to oversee network-wide operations, drive efficiency, manage a large multi-site team, and ensure on-time delivery performance at scale.', company: 'RecX Direct Client', location: 'Midlands, UK', workModel: 'onsite', industry: 'Operations & Logistics', seniorityLevel: 'executive', salaryMin: 90000, salaryMax: 120000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T10:00:00.000Z', splitAmount: 12000, splitCurrency: 'USD' },
  { id: 'r-038', source: 'recx_direct', title: 'Account Manager - Pharma', descriptionSnippet: 'A pharmaceutical company in the South East is seeking an experienced Account Manager to manage and grow a portfolio of NHS and private accounts. Life sciences background and strong understanding of NHS commissioning required.', company: 'RecX Direct Client', location: 'South East, UK', workModel: 'remote', industry: 'Sales', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T11:00:00.000Z', splitAmount: 6000, splitCurrency: 'USD' },
  { id: 'r-039', source: 'xchange', title: 'Product Manager - B2B Platform', descriptionSnippet: 'Technical PM to own enterprise product roadmap. Strong API/platform experience, agile methodology, and stakeholder management. Computer science background preferred.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 75000, salaryMax: 105000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-23T09:00:00.000Z', splitAmount: 9000, splitCurrency: 'GBP' },
  { id: 'r-040', source: 'recx_direct', title: 'Commissioning Engineer - HVAC', descriptionSnippet: 'A specialist commissioning company in the UK is seeking a Commissioning Engineer with solid HVAC experience to commission complex mechanical systems on commercial and life sciences projects.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 40000, salaryMax: 55000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T09:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-041', source: 'recx_direct', title: 'Psychotherapist - Private Practice', descriptionSnippet: 'A growing private therapy network across multiple UK cities is seeking qualified Psychotherapists to deliver CBT and integrative therapy to a mixed adult caseload. BACP or UKCP accreditation required.', company: 'RecX Direct Client', location: 'Multiple UK Locations', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 52000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T10:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-042', source: 'xchange', title: 'Legal Counsel - Commercial', descriptionSnippet: 'Commercial lawyer for high-growth tech company. Contract negotiation, SaaS agreements, M&A support. Common law qualification required, in-house experience preferred.', company: 'Xchange Partner', location: 'Dubai, UAE', workModel: 'onsite', industry: 'Legal', seniorityLevel: 'senior', salaryMin: 120000, salaryMax: 180000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-15T07:00:00.000Z', splitAmount: 20000, splitCurrency: 'USD' },
];

// ─── BATCH 2: Roles 43–85 ────────────────────────────────────────────────────
const ROLES_BATCH_2: Role[] = [
  { id: 'r-043', source: 'recx_direct', title: 'Procurement Manager - Construction', descriptionSnippet: 'A leading main contractor is seeking a Procurement Manager to manage subcontractor procurement and supply chain relationships across multiple live projects. Strong NEC/JCT contract knowledge and negotiation skills required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 60000, salaryMax: 80000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-01T07:00:00.000Z', splitAmount: 8000, splitCurrency: 'USD' },
  { id: 'r-044', source: 'xchange', title: 'Senior Frontend Developer', descriptionSnippet: 'React specialist for consumer-facing product. Modern stack including Next.js, TypeScript and Tailwind, design systems, performance optimisation and strong UX sensibility required.', company: 'Xchange Partner', location: 'Amsterdam, Netherlands', workModel: 'remote', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 70000, salaryMax: 95000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-16T12:00:00.000Z', splitAmount: 8500, splitCurrency: 'EUR' },
  { id: 'r-045', source: 'recx_direct', title: 'Substance Misuse Practitioner', descriptionSnippet: 'A community substance misuse service in Yorkshire is seeking an experienced Practitioner to provide assessment, key working and recovery support to adults with drug and alcohol dependencies. NVQ Level 4 or equivalent required.', company: 'RecX Direct Client', location: 'Yorkshire, UK', workModel: 'onsite', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 28000, salaryMax: 38000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-02T07:00:00.000Z', splitAmount: 3500, splitCurrency: 'USD' },
  { id: 'r-046', source: 'recx_direct', title: 'Quality Manager - Aerospace', descriptionSnippet: 'A precision engineering company supplying the aerospace sector is hiring a Quality Manager to lead AS9100 compliance, internal audits, PPAP submissions and supplier quality assurance programmes.', company: 'RecX Direct Client', location: 'Bristol, UK', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T07:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
  { id: 'r-047', source: 'xchange', title: 'Data Scientist - Personalisation', descriptionSnippet: 'ML-focused data scientist for personalisation engine at a global e-commerce platform. Python, scikit-learn, SQL, A/B testing and experience with recommendation systems required.', company: 'Xchange Partner', location: 'Toronto, Canada', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 100000, salaryMax: 140000, salaryCurrency: 'CAD', roleType: 'permanent', postedAt: '2026-02-24T10:00:00.000Z', splitAmount: 13000, splitCurrency: 'CAD' },
  { id: 'r-048', source: 'recx_direct', title: 'General Manager - Hospitality', descriptionSnippet: 'A well-regarded hotel group is seeking a General Manager for a flagship property in the South of England. Full P&L accountability, team leadership across all departments, and strong guest experience delivery required.', company: 'RecX Direct Client', location: 'Hampshire, UK', workModel: 'onsite', industry: 'Hospitality & Leisure', seniorityLevel: 'executive', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T07:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
  { id: 'r-049', source: 'recx_direct', title: 'Midwife - Band 6', descriptionSnippet: 'An NHS Trust in the North West is seeking a Band 6 Midwife to provide high-quality antenatal, intrapartum and postnatal care. NMC registration, mentoring experience and a passion for woman-centred care required.', company: 'RecX Direct Client', location: 'Liverpool, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 37000, salaryMax: 44000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T07:00:00.000Z', splitAmount: 4000, splitCurrency: 'USD' },
  { id: 'r-050', source: 'xchange', title: 'VP of Sales - SaaS', descriptionSnippet: 'A Series B SaaS company is seeking a VP of Sales to lead and scale a high-performance sales organisation. Experience building enterprise sales teams in a fast-growth environment, strong CRO collaboration and data-driven forecasting required.', company: 'Xchange Partner', location: 'San Francisco, CA, USA', workModel: 'hybrid', industry: 'Sales', seniorityLevel: 'executive', salaryMin: 200000, salaryMax: 280000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-14T09:00:00.000Z', splitAmount: 28000, splitCurrency: 'USD' },
  { id: 'r-051', source: 'recx_direct', title: 'Civil Engineer - Highways', descriptionSnippet: 'A highways consultancy in the South West is seeking a Civil Engineer with experience in highways design and infrastructure delivery. AutoCAD, Civil 3D and knowledge of DMRB standards required.', company: 'RecX Direct Client', location: 'Bristol, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 52000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-06T07:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-052', source: 'recx_direct', title: 'Forensic Social Worker', descriptionSnippet: 'A specialist forensic mental health service is seeking a qualified Social Worker to work within a multi-disciplinary team supporting offenders with complex mental health needs. HCPC registration and forensic experience essential.', company: 'RecX Direct Client', location: 'West Midlands, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 36000, salaryMax: 46000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T07:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-053', source: 'xchange', title: 'Chief Financial Officer', descriptionSnippet: 'A private equity-backed manufacturing business is seeking a CFO to lead all financial operations, drive strategic growth, and support an eventual exit. ACA/ACCA qualified with PE-backed business experience preferred.', company: 'Xchange Partner', location: 'Midlands, UK', workModel: 'onsite', industry: 'Finance & Accounting', seniorityLevel: 'executive', salaryMin: 150000, salaryMax: 200000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-10T09:00:00.000Z', splitAmount: 22000, splitCurrency: 'GBP' },
  { id: 'r-054', source: 'recx_direct', title: 'Supply Chain Manager', descriptionSnippet: 'A global FMCG business is seeking a Supply Chain Manager to oversee end-to-end supply chain operations including procurement, inventory, logistics and supplier management across European markets.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Operations & Logistics', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T07:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
  { id: 'r-055', source: 'recx_direct', title: 'Paediatric Nurse', descriptionSnippet: "A children's hospital in the West Midlands is seeking a qualified Paediatric Nurse to join a busy medical ward. RSCN or RN Child qualification required, with experience in acute paediatric settings.", company: 'RecX Direct Client', location: 'Birmingham, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 33000, salaryMax: 41000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T07:00:00.000Z', splitAmount: 4000, splitCurrency: 'USD' },
  { id: 'r-056', source: 'xchange', title: 'SEO & Content Strategist', descriptionSnippet: 'A digital marketing agency is hiring an SEO and Content Strategist to lead organic growth campaigns for a portfolio of B2B clients. Technical SEO, content planning, and strong data analysis skills required.', company: 'Xchange Partner', location: 'Remote (UK)', workModel: 'remote', industry: 'Marketing', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 52000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-25T09:00:00.000Z', splitAmount: 5000, splitCurrency: 'GBP' },
  { id: 'r-057', source: 'recx_direct', title: 'Project Manager - Data Centre', descriptionSnippet: 'A specialist data centre construction company is seeking a Project Manager to deliver hyperscale projects across the UK and Europe. Strong MEP knowledge, PRINCE2 or APM qualified, and prior data centre experience essential.', company: 'RecX Direct Client', location: 'United Kingdom / Europe', workModel: 'onsite', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 70000, salaryMax: 95000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T07:00:00.000Z', splitAmount: 10000, splitCurrency: 'USD' },
  { id: 'r-058', source: 'recx_direct', title: 'Occupational Therapist - Community', descriptionSnippet: 'A community health team in Scotland is seeking a qualified Occupational Therapist to support adults with physical and cognitive disabilities to maintain independence at home. HCPC registration required.', company: 'RecX Direct Client', location: 'Scotland, UK', workModel: 'hybrid', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 33000, salaryMax: 43000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T07:00:00.000Z', splitAmount: 4200, splitCurrency: 'USD' },
  { id: 'r-059', source: 'xchange', title: 'Head of Engineering', descriptionSnippet: 'A scale-up fintech company is seeking a Head of Engineering to lead a distributed team of 30+ engineers. Strong technical leadership, architecture decision-making, and experience scaling engineering orgs in regulated environments required.', company: 'Xchange Partner', location: 'Dublin, Ireland', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'executive', salaryMin: 160000, salaryMax: 210000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-12T09:00:00.000Z', splitAmount: 20000, splitCurrency: 'EUR' },
  { id: 'r-060', source: 'recx_direct', title: 'Learning & Development Manager', descriptionSnippet: 'A large retail business is seeking an L&D Manager to design and deliver learning programmes across the organisation. Experience in blended learning, LMS management and leadership development essential.', company: 'RecX Direct Client', location: 'Leeds, UK', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 58000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-12T07:00:00.000Z', splitAmount: 6000, splitCurrency: 'USD' },
  { id: 'r-061', source: 'recx_direct', title: 'Automation Engineer - FMCG', descriptionSnippet: 'A leading food and beverage manufacturer is seeking an Automation Engineer to maintain, improve and develop PLC-controlled production lines. Siemens TIA Portal and SCADA experience required.', company: 'RecX Direct Client', location: 'Warwickshire, UK', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 42000, salaryMax: 58000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-01T10:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-062', source: 'xchange', title: 'Compliance Manager - Financial Services', descriptionSnippet: 'A regulated financial services firm in Singapore is seeking a Compliance Manager to oversee MAS regulatory compliance, AML/CFT frameworks and governance reporting. Strong knowledge of MAS guidelines required.', company: 'Xchange Partner', location: 'Singapore', workModel: 'hybrid', industry: 'Legal', seniorityLevel: 'senior', salaryMin: 100000, salaryMax: 140000, salaryCurrency: 'SGD', roleType: 'permanent', postedAt: '2026-02-13T09:00:00.000Z', splitAmount: 12000, splitCurrency: 'SGD' },
  { id: 'r-063', source: 'recx_direct', title: 'Head Chef - Fine Dining', descriptionSnippet: 'A Michelin-recommended restaurant group in London is seeking a Head Chef for a flagship venue. You will lead a brigade of 15, drive seasonal menu development, manage food costs, and maintain the highest culinary standards.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'onsite', industry: 'Hospitality & Leisure', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-02T10:00:00.000Z', splitAmount: 7500, splitCurrency: 'USD' },
  { id: 'r-064', source: 'recx_direct', title: 'Technical Sales Engineer - Pumps & Valves', descriptionSnippet: 'A fluid handling equipment specialist is seeking a Technical Sales Engineer to grow revenue across the oil, gas and water treatment sectors. Engineering degree and field sales experience in industrial process equipment required.', company: 'RecX Direct Client', location: 'Aberdeen, UK', workModel: 'remote', industry: 'Sales', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T10:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
  { id: 'r-065', source: 'xchange', title: 'Renewable Energy Project Developer', descriptionSnippet: 'A clean energy developer is seeking a Project Developer to manage the development pipeline for solar and wind assets across the UK. Planning, grid connection, land rights and consenting experience required.', company: 'Xchange Partner', location: 'United Kingdom', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-26T09:00:00.000Z', splitAmount: 9500, splitCurrency: 'GBP' },
  { id: 'r-066', source: 'recx_direct', title: 'Recruitment Consultant - Technology', descriptionSnippet: 'A specialist technology recruitment firm in London is seeking a Recruitment Consultant to manage the full 360 desk, placing software engineers and product professionals across the UK tech market.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'mid', salaryMin: 30000, salaryMax: 45000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T07:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-067', source: 'recx_direct', title: 'Registered Mental Health Nurse - Inpatient', descriptionSnippet: 'A private inpatient mental health hospital in the South East is seeking a Registered Mental Health Nurse to work across acute adult wards. RMN qualification, NMC registration and inpatient experience required.', company: 'RecX Direct Client', location: 'Surrey, UK', workModel: 'onsite', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 36000, salaryMax: 46000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T07:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-068', source: 'xchange', title: 'Brand Manager - Consumer Goods', descriptionSnippet: 'A leading consumer goods company is seeking a Brand Manager to drive P&L performance, campaign planning, and NPD for a key brand in their portfolio. Strong FMCG brand management background required.', company: 'Xchange Partner', location: 'Sydney, Australia', workModel: 'hybrid', industry: 'Marketing', seniorityLevel: 'mid', salaryMin: 100000, salaryMax: 130000, salaryCurrency: 'AUD', roleType: 'permanent', postedAt: '2026-02-27T09:00:00.000Z', splitAmount: 11000, splitCurrency: 'AUD' },
  { id: 'r-069', source: 'recx_direct', title: 'Warehouse Manager', descriptionSnippet: 'A logistics and distribution company in the East of England is seeking a Warehouse Manager to oversee daily warehouse operations, team management, KPI delivery and Health & Safety compliance across a large distribution centre.', company: 'RecX Direct Client', location: 'Peterborough, UK', workModel: 'onsite', industry: 'Operations & Logistics', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 50000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-06T07:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-070', source: 'recx_direct', title: 'Bid Manager - Infrastructure', descriptionSnippet: 'A major infrastructure contractor is seeking a Bid Manager to lead the preparation and submission of high-value tenders across water, highways and rail sectors. Strong writing, coordination and stakeholder management skills required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T07:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
  { id: 'r-071', source: 'xchange', title: 'Investment Analyst - Private Equity', descriptionSnippet: 'A mid-market private equity fund in London is seeking an Investment Analyst to support deal origination, financial modelling and portfolio management. Strong Excel modelling, CIM analysis and transaction experience required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'onsite', industry: 'Finance & Accounting', seniorityLevel: 'mid', salaryMin: 70000, salaryMax: 100000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-11T09:00:00.000Z', splitAmount: 11000, splitCurrency: 'GBP' },
  { id: 'r-072', source: 'recx_direct', title: 'Clinical Psychologist', descriptionSnippet: 'A NHS IAPT service in London is seeking a Clinical Psychologist to deliver evidence-based psychological therapies to adults with anxiety and depression. HCPC registration and BPS accreditation required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 72000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T07:00:00.000Z', splitAmount: 7500, splitCurrency: 'USD' },
  { id: 'r-073', source: 'recx_direct', title: 'Plant Engineer - Oil & Gas', descriptionSnippet: 'A major oil and gas operator on the UKCS is seeking a Plant Engineer to provide technical support for rotating and static equipment. Offshore experience, HNC/BEng in Mechanical Engineering and BOSIET certification required.', company: 'RecX Direct Client', location: 'Aberdeen, UK (Offshore)', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'senior', salaryMin: 70000, salaryMax: 95000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T07:00:00.000Z', splitAmount: 10000, splitCurrency: 'USD' },
  { id: 'r-074', source: 'xchange', title: 'Cybersecurity Analyst', descriptionSnippet: 'A financial services firm in New York is seeking a Cybersecurity Analyst to monitor threats, conduct vulnerability assessments and support incident response. CISSP or CEH certification and SOC experience required.', company: 'Xchange Partner', location: 'New York, USA', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 110000, salaryMax: 145000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-28T09:00:00.000Z', splitAmount: 13000, splitCurrency: 'USD' },
  { id: 'r-075', source: 'recx_direct', title: 'Events Manager - Corporate', descriptionSnippet: 'A corporate events agency in London is seeking an Events Manager to plan and deliver high-profile client events including conferences, product launches and incentive travel. Strong project management and supplier negotiation skills required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Hospitality & Leisure', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 50000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T07:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-076', source: 'recx_direct', title: 'Environmental Consultant', descriptionSnippet: 'A multi-disciplinary environmental consultancy is seeking an Environmental Consultant to deliver EIAs, ecological surveys and planning support for infrastructure and development projects across the UK.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 50000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T07:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-077', source: 'xchange', title: 'Solicitor - Employment Law', descriptionSnippet: 'A top-tier UK law firm is seeking an Employment Law Solicitor to advise on a broad range of contentious and non-contentious matters for corporate clients. 3+ years PQE in employment law required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Legal', seniorityLevel: 'mid', salaryMin: 65000, salaryMax: 90000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-09T09:00:00.000Z', splitAmount: 9000, splitCurrency: 'GBP' },
  { id: 'r-078', source: 'recx_direct', title: 'Store Manager - Fashion Retail', descriptionSnippet: 'A premium fashion retailer is seeking a Store Manager for a flagship London store. You will drive sales performance, develop a high-performing team and deliver an exceptional customer experience in line with brand standards.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'onsite', industry: 'Retail & Consumer', seniorityLevel: 'mid', salaryMin: 38000, salaryMax: 50000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-12T07:00:00.000Z', splitAmount: 5000, splitCurrency: 'USD' },
  { id: 'r-079', source: 'recx_direct', title: 'Safety Critical Maintenance Technician', descriptionSnippet: 'A rail infrastructure company is seeking a Safety Critical Maintenance Technician to carry out planned and reactive maintenance on signalling and track systems. PTS certification and relevant maintenance experience required.', company: 'RecX Direct Client', location: 'Nationwide, UK', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 48000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-01T12:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-080', source: 'xchange', title: 'UX/UI Designer - FinTech', descriptionSnippet: 'A growing fintech startup in Amsterdam is seeking a UX/UI Designer to lead product design across web and mobile. Strong Figma skills, user research capability and experience designing financial products required.', company: 'Xchange Partner', location: 'Amsterdam, Netherlands', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-07T09:00:00.000Z', splitAmount: 8500, splitCurrency: 'EUR' },
  { id: 'r-081', source: 'recx_direct', title: 'Physiotherapist - MSK', descriptionSnippet: 'A private MSK physiotherapy clinic with multiple sites across the UK is seeking a qualified Physiotherapist. HCPC registration and experience in musculoskeletal assessment and rehabilitation required.', company: 'RecX Direct Client', location: 'Multiple UK Locations', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 48000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-02T12:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
  { id: 'r-082', source: 'recx_direct', title: 'Area Sales Manager - Building Materials', descriptionSnippet: 'A leading building materials manufacturer is seeking an Area Sales Manager to grow revenue across the South East. You will manage a portfolio of merchant and contractor accounts and drive specification through architects and developers.', company: 'RecX Direct Client', location: 'South East, UK', workModel: 'remote', industry: 'Sales', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T12:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
  { id: 'r-083', source: 'xchange', title: 'Chief People Officer', descriptionSnippet: 'A high-growth technology company is seeking a Chief People Officer to lead all people strategy including talent acquisition, culture, compensation and organisational development. Prior CPO or CHRO experience in a tech scale-up required.', company: 'Xchange Partner', location: 'Remote (US or UK)', workModel: 'remote', industry: 'Human Resources', seniorityLevel: 'executive', salaryMin: 180000, salaryMax: 240000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-06T09:00:00.000Z', splitAmount: 24000, splitCurrency: 'USD' },
  { id: 'r-084', source: 'recx_direct', title: 'Estimator - M&E', descriptionSnippet: 'A specialist M&E contractor is seeking an experienced Estimator to price mechanical and electrical packages on commercial, industrial and residential projects. Strong knowledge of labour rates, material pricing and subcontractor negotiation required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'mid', salaryMin: 50000, salaryMax: 65000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T12:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
  { id: 'r-085', source: 'recx_direct', title: 'Night Nurse - Care Home', descriptionSnippet: 'A residential care home group in the North West is seeking a qualified Night Nurse to provide clinical oversight and care to elderly residents overnight. NMC registration and care home or community nursing experience required.', company: 'RecX Direct Client', location: 'Lancashire, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 33000, salaryMax: 42000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T12:00:00.000Z', splitAmount: 4000, splitCurrency: 'USD' },
];

// ─── BATCH 3a: Roles 86–106 ─────────────────────────────────────────────────
const ROLES_BATCH_3: Role[] = [
  { id: 'r-086', source: 'recx_direct', title: 'Neonatal Nurse', descriptionSnippet: 'A specialist neonatal unit at a large NHS hospital in the North East is seeking an experienced Neonatal Nurse. NMC registration, NICU experience and competency in caring for premature and critically ill newborns required.', company: 'RecX Direct Client', location: 'Newcastle, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 34000, salaryMax: 44000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-06T12:00:00.000Z', splitAmount: 4200, splitCurrency: 'USD' },
  { id: 'r-087', source: 'xchange', title: 'Backend Engineer - Golang', descriptionSnippet: 'A high-scale fintech platform is seeking a Backend Engineer with strong Golang expertise to build microservices and APIs handling millions of daily transactions. gRPC, Kubernetes and distributed systems experience required.', company: 'Xchange Partner', location: 'Remote (Europe)', workModel: 'remote', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 90000, salaryMax: 125000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-05T09:00:00.000Z', splitAmount: 12000, splitCurrency: 'EUR' },
  { id: 'r-088', source: 'recx_direct', title: 'M&E Quantity Surveyor', descriptionSnippet: 'A leading M&E contractor is seeking a Quantity Surveyor to manage the commercial function on a major data centre project. Strong NEC contract knowledge, CVR management and subcontract procurement experience required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T12:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
  { id: 'r-089', source: 'recx_direct', title: 'Dual Diagnosis Practitioner', descriptionSnippet: 'A community mental health and substance misuse service in Greater Manchester is seeking a Dual Diagnosis Practitioner to support clients with co-occurring mental health and addiction needs. RMN or social work qualification required.', company: 'RecX Direct Client', location: 'Manchester, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'mid', salaryMin: 32000, salaryMax: 42000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T12:00:00.000Z', splitAmount: 4000, splitCurrency: 'USD' },
  { id: 'r-090', source: 'xchange', title: 'Treasury Manager', descriptionSnippet: 'A multinational corporation in Zurich is seeking a Treasury Manager to oversee cash management, FX hedging and liquidity planning across global entities. ACT qualified with 5+ years corporate treasury experience required.', company: 'Xchange Partner', location: 'Zurich, Switzerland', workModel: 'hybrid', industry: 'Finance & Accounting', seniorityLevel: 'senior', salaryMin: 110000, salaryMax: 145000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-02-04T09:00:00.000Z', splitAmount: 14000, splitCurrency: 'EUR' },
  { id: 'r-091', source: 'recx_direct', title: 'Senior Quantity Surveyor - Residential', descriptionSnippet: 'A leading house builder is seeking a Senior Quantity Surveyor to manage costs on high-volume residential schemes. Strong subcontract procurement, CVR reporting and final account experience required.', company: 'RecX Direct Client', location: 'South East, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 60000, salaryMax: 80000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T12:00:00.000Z', splitAmount: 8500, splitCurrency: 'USD' },
  { id: 'r-092', source: 'xchange', title: 'Enterprise Account Executive', descriptionSnippet: 'A SaaS company in Chicago is seeking an Enterprise AE to close complex, multi-stakeholder deals with Fortune 500 clients. 5+ years enterprise software sales experience and strong MEDDIC methodology knowledge required.', company: 'Xchange Partner', location: 'Chicago, IL, USA', workModel: 'hybrid', industry: 'Sales', seniorityLevel: 'senior', salaryMin: 140000, salaryMax: 200000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-02-03T09:00:00.000Z', splitAmount: 20000, splitCurrency: 'USD' },
  { id: 'r-093', source: 'recx_direct', title: 'Mechanical Design Engineer', descriptionSnippet: 'A precision engineering business in the East Midlands is seeking a Mechanical Design Engineer to develop product designs from concept through to manufacture. SolidWorks or CATIA proficiency and GD&T knowledge required.', company: 'RecX Direct Client', location: 'Nottingham, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 40000, salaryMax: 55000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T12:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-094', source: 'recx_direct', title: 'Speech and Language Therapist', descriptionSnippet: 'A community NHS trust in Wales is seeking a qualified Speech and Language Therapist to manage an adult caseload including dysphagia and communication disorders. HCPC registration and RCSLT membership required.', company: 'RecX Direct Client', location: 'Wales, UK', workModel: 'hybrid', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 33000, salaryMax: 44000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T12:00:00.000Z', splitAmount: 4200, splitCurrency: 'USD' },
  { id: 'r-095', source: 'xchange', title: 'Director of Product - Marketplace', descriptionSnippet: 'A high-growth marketplace platform is seeking a Director of Product to own the full product strategy. Experience leading product teams, driving GMV growth, and managing complex two-sided marketplace dynamics required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'executive', salaryMin: 140000, salaryMax: 190000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-02T09:00:00.000Z', splitAmount: 19000, splitCurrency: 'GBP' },
  { id: 'r-096', source: 'recx_direct', title: 'Key Account Manager - Industrial Gases', descriptionSnippet: 'A global industrial gases supplier is seeking a Key Account Manager to manage and grow strategic accounts across UK manufacturing and process industries. Technical sales background and understanding of gas applications required.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'remote', industry: 'Sales', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 72000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-12T12:00:00.000Z', splitAmount: 7500, splitCurrency: 'USD' },
  { id: 'r-097', source: 'recx_direct', title: 'Approved Mental Health Professional', descriptionSnippet: 'A local authority in the South West is seeking an Approved Mental Health Professional to carry out statutory assessments under the Mental Health Act and support complex cases within a busy AMHP service. AMHP warrant and social work degree required.', company: 'RecX Direct Client', location: 'South West, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'senior', salaryMin: 42000, salaryMax: 56000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-01T13:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
  { id: 'r-098', source: 'xchange', title: 'Partnerships Manager - FinTech', descriptionSnippet: 'A payments technology company is seeking a Partnerships Manager to identify, negotiate and manage strategic integrations with banks, fintechs and enterprise clients across Europe. Strong commercial and technical partner management experience required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Sales', seniorityLevel: 'mid', salaryMin: 65000, salaryMax: 90000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-02-01T09:00:00.000Z', splitAmount: 9500, splitCurrency: 'GBP' },
  { id: 'r-099', source: 'recx_direct', title: 'Fire Protection Engineer', descriptionSnippet: 'A specialist fire engineering consultancy is seeking a Fire Protection Engineer to deliver fire safety strategies, sprinkler system designs and fire risk assessments for commercial and residential developments.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 62000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-02T13:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
  { id: 'r-100', source: 'xchange', title: 'Regional Director - Care Services', descriptionSnippet: 'A national care provider is seeking a Regional Director to oversee quality, compliance and commercial performance across a portfolio of residential and supported living services in the South of England. RGN or social work background preferred.', company: 'Xchange Partner', location: 'South England, UK', workModel: 'hybrid', industry: 'Healthcare & Nursing', seniorityLevel: 'executive', salaryMin: 85000, salaryMax: 110000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-01-31T09:00:00.000Z', splitAmount: 12000, splitCurrency: 'GBP' },
  { id: 'r-101', source: 'recx_direct', title: 'Recruitment Manager - In-House', descriptionSnippet: 'A fast-growing professional services firm is seeking a Recruitment Manager to lead internal talent acquisition, build direct sourcing strategies and manage a small TA team across multiple business units.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'senior', salaryMin: 55000, salaryMax: 72000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-03T13:00:00.000Z', splitAmount: 7500, splitCurrency: 'USD' },
  { id: 'r-102', source: 'recx_direct', title: 'Heating & Plumbing Engineer', descriptionSnippet: 'A building services contractor in the North West is seeking an experienced Heating and Plumbing Engineer to carry out installation and commissioning of commercial heating systems. Gas Safe registered and City & Guilds qualified required.', company: 'RecX Direct Client', location: 'North West, UK', workModel: 'onsite', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 36000, salaryMax: 48000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-04T13:00:00.000Z', splitAmount: 4800, splitCurrency: 'USD' },
  { id: 'r-103', source: 'xchange', title: 'M&A Associate', descriptionSnippet: 'A mid-market investment bank in Paris is seeking an M&A Associate to support transaction execution including financial modelling, due diligence coordination and client presentations. 2+ years M&A or corporate finance experience required.', company: 'Xchange Partner', location: 'Paris, France', workModel: 'onsite', industry: 'Finance & Accounting', seniorityLevel: 'mid', salaryMin: 90000, salaryMax: 130000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-01-30T09:00:00.000Z', splitAmount: 13000, splitCurrency: 'EUR' },
  { id: 'r-104', source: 'recx_direct', title: 'Category Manager - Retail', descriptionSnippet: 'A major UK grocery retailer is seeking a Category Manager to develop and execute range, space and promotional plans for a key product category. Strong commercial acumen, supplier negotiation and data analysis skills required.', company: 'RecX Direct Client', location: 'Leeds, UK', workModel: 'hybrid', industry: 'Retail & Consumer', seniorityLevel: 'mid', salaryMin: 45000, salaryMax: 60000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-05T13:00:00.000Z', splitAmount: 6000, splitCurrency: 'USD' },
  { id: 'r-105', source: 'xchange', title: 'Growth Marketing Manager', descriptionSnippet: 'A Series A consumer tech company is seeking a Growth Marketing Manager to own performance marketing channels including paid social, SEM and lifecycle email. Strong analytical skills and hands-on paid media experience required.', company: 'Xchange Partner', location: 'Remote (UK)', workModel: 'remote', industry: 'Marketing', seniorityLevel: 'mid', salaryMin: 55000, salaryMax: 72000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-01-29T09:00:00.000Z', splitAmount: 7500, splitCurrency: 'GBP' },
  { id: 'r-106', source: 'recx_direct', title: 'Contracts Manager - Civils', descriptionSnippet: 'A civils and infrastructure contractor is seeking a Contracts Manager to oversee delivery of multiple ground engineering and drainage projects simultaneously. Strong NEC3/4 experience, programme management and client relationship skills required.', company: 'RecX Direct Client', location: 'Midlands, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-06T13:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
{ id: 'r-107', source: 'recx_direct', title: 'Registered Nurse - Theatre', descriptionSnippet: 'A private hospital group in London is seeking an experienced Theatre Nurse to scrub and circulate across general surgical and orthopaedic lists. NMC registration and post-registration theatre experience required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 36000, salaryMax: 46000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-07T13:00:00.000Z', splitAmount: 4500, splitCurrency: 'USD' },
{ id: 'r-108', source: 'xchange', title: 'Senior Data Engineer', descriptionSnippet: 'A data-driven e-commerce business in Berlin is seeking a Senior Data Engineer to build and maintain scalable data pipelines. Strong Python, Apache Spark, dbt and cloud data warehouse experience required.', company: 'Xchange Partner', location: 'Berlin, Germany', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'senior', salaryMin: 85000, salaryMax: 115000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-01-28T09:00:00.000Z', splitAmount: 11000, splitCurrency: 'EUR' },
{ id: 'r-109', source: 'recx_direct', title: 'Façade Engineer', descriptionSnippet: 'A specialist façade consultancy in London is seeking a Façade Engineer to deliver technical design and site supervision on high-profile commercial and residential curtain wall and cladding projects.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 48000, salaryMax: 65000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-08T13:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
{ id: 'r-110', source: 'recx_direct', title: 'Consultant Psychiatrist', descriptionSnippet: 'A private mental health hospital in the South East is seeking a Consultant Psychiatrist to lead clinical care across an adult inpatient unit. Full GMC registration, Section 12 approval and MRCPsych required.', company: 'RecX Direct Client', location: 'Surrey, UK', workModel: 'onsite', industry: 'Mental Health & Wellbeing', seniorityLevel: 'executive', salaryMin: 130000, salaryMax: 160000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-09T13:00:00.000Z', splitAmount: 16000, splitCurrency: 'USD' },
{ id: 'r-111', source: 'xchange', title: 'Logistics Operations Manager', descriptionSnippet: 'A global freight and logistics company in Dubai is seeking an Operations Manager to oversee air and sea freight operations across the Middle East region. Strong IATA knowledge and multi-modal logistics experience required.', company: 'Xchange Partner', location: 'Dubai, UAE', workModel: 'onsite', industry: 'Operations & Logistics', seniorityLevel: 'senior', salaryMin: 90000, salaryMax: 120000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-01-27T09:00:00.000Z', splitAmount: 12000, splitCurrency: 'USD' },
{ id: 'r-112', source: 'recx_direct', title: 'Quantity Surveyor - Fit Out', descriptionSnippet: 'A commercial fit out contractor in London is seeking a Quantity Surveyor to manage costs on high-end office and retail refurbishment projects. JCT contract knowledge and strong subcontract procurement experience required.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'mid', salaryMin: 48000, salaryMax: 65000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-10T13:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
{ id: 'r-113', source: 'xchange', title: 'Customer Success Manager - SaaS', descriptionSnippet: 'A B2B SaaS platform in Stockholm is seeking a Customer Success Manager to onboard enterprise clients, drive adoption and reduce churn. Strong relationship management, QBR delivery and data-driven account health monitoring required.', company: 'Xchange Partner', location: 'Stockholm, Sweden', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-01-26T09:00:00.000Z', splitAmount: 8500, splitCurrency: 'EUR' },
{ id: 'r-114', source: 'recx_direct', title: 'District Nurse', descriptionSnippet: 'An NHS community trust in Yorkshire is seeking a qualified District Nurse to manage a caseload of housebound patients requiring complex wound care, medication management and end-of-life support. NMC registration and community nursing experience required.', company: 'RecX Direct Client', location: 'Yorkshire, UK', workModel: 'hybrid', industry: 'Healthcare & Nursing', seniorityLevel: 'mid', salaryMin: 35000, salaryMax: 44000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-11T13:00:00.000Z', splitAmount: 4200, splitCurrency: 'USD' },
{ id: 'r-115', source: 'recx_direct', title: 'Commercial Manager - Infrastructure', descriptionSnippet: 'A major infrastructure contractor is seeking a Commercial Manager to lead the commercial function on a high-value highways framework. Strong NEC4 contract experience, CVR management and supply chain procurement skills required.', company: 'RecX Direct Client', location: 'Midlands, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 75000, salaryMax: 95000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-12T13:00:00.000Z', splitAmount: 10000, splitCurrency: 'USD' },
{ id: 'r-116', source: 'xchange', title: 'Principal Structural Engineer', descriptionSnippet: 'A multidisciplinary consultancy in Sydney is seeking a Principal Structural Engineer to lead complex commercial and infrastructure projects. Chartered status, strong client management and experience mentoring junior engineers required.', company: 'Xchange Partner', location: 'Sydney, Australia', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'executive', salaryMin: 160000, salaryMax: 210000, salaryCurrency: 'AUD', roleType: 'permanent', postedAt: '2026-01-25T09:00:00.000Z', splitAmount: 18000, splitCurrency: 'AUD' },
{ id: 'r-117', source: 'recx_direct', title: 'Internal Communications Manager', descriptionSnippet: 'A large UK professional services firm is seeking an Internal Communications Manager to develop and deliver employee engagement campaigns, leadership messaging and change communications across a dispersed workforce.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Marketing', seniorityLevel: 'mid', salaryMin: 48000, salaryMax: 62000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T07:00:00.000Z', splitAmount: 6500, splitCurrency: 'USD' },
{ id: 'r-118', source: 'xchange', title: 'Risk Manager - Financial Services', descriptionSnippet: 'A global investment bank in London is seeking a Risk Manager to oversee operational and credit risk frameworks across EMEA. FRM or PRM qualification, strong regulatory knowledge and prior risk management experience in financial services required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Finance & Accounting', seniorityLevel: 'senior', salaryMin: 95000, salaryMax: 130000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-01-24T09:00:00.000Z', splitAmount: 13000, splitCurrency: 'GBP' },
{ id: 'r-119', source: 'recx_direct', title: 'BIM Manager', descriptionSnippet: 'A leading main contractor is seeking a BIM Manager to lead digital delivery across multiple live construction projects. Revit, Navisworks and strong ISO 19650 knowledge required, with experience managing BIM execution plans and CDE environments.', company: 'RecX Direct Client', location: 'London, UK', workModel: 'hybrid', industry: 'Construction & Facilities', seniorityLevel: 'senior', salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T08:00:00.000Z', splitAmount: 9000, splitCurrency: 'USD' },
{ id: 'r-120', source: 'xchange', title: 'Talent Partner - Engineering', descriptionSnippet: 'A global engineering consultancy is seeking a Talent Partner to manage end-to-end hiring for technical and engineering roles across EMEA. Direct sourcing, stakeholder management and experience hiring niche engineering disciplines required.', company: 'Xchange Partner', location: 'Amsterdam, Netherlands', workModel: 'hybrid', industry: 'Human Resources', seniorityLevel: 'mid', salaryMin: 60000, salaryMax: 80000, salaryCurrency: 'EUR', roleType: 'permanent', postedAt: '2026-01-23T09:00:00.000Z', splitAmount: 8000, splitCurrency: 'EUR' },
{ id: 'r-121', source: 'recx_direct', title: 'Senior Mental Health Social Worker', descriptionSnippet: 'A community mental health team in the North West is seeking a Senior Mental Health Social Worker to hold a complex caseload and provide supervision to junior practitioners. HCPC registration, AMHP eligibility and post-qualifying experience required.', company: 'RecX Direct Client', location: 'Manchester, UK', workModel: 'hybrid', industry: 'Mental Health & Wellbeing', seniorityLevel: 'senior', salaryMin: 42000, salaryMax: 54000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T09:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
{ id: 'r-122', source: 'xchange', title: 'Solutions Engineer - Pre-Sales', descriptionSnippet: 'A enterprise software company in New York is seeking a Solutions Engineer to support the sales team with technical discovery, product demos and proof of concept builds. Strong API knowledge, scripting skills and client-facing experience required.', company: 'Xchange Partner', location: 'New York, USA', workModel: 'hybrid', industry: 'Technology', seniorityLevel: 'mid', salaryMin: 120000, salaryMax: 155000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-01-22T09:00:00.000Z', splitAmount: 15000, splitCurrency: 'USD' },
{ id: 'r-123', source: 'recx_direct', title: 'Geotechnical Engineer', descriptionSnippet: 'A specialist geotechnical consultancy is seeking a Geotechnical Engineer to deliver ground investigation, slope stability and foundation design work across infrastructure and residential development projects throughout the UK.', company: 'RecX Direct Client', location: 'United Kingdom', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 42000, salaryMax: 58000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T10:00:00.000Z', splitAmount: 6000, splitCurrency: 'USD' },
{ id: 'r-124', source: 'recx_direct', title: 'Ward Manager - Acute Medicine', descriptionSnippet: 'An NHS Trust in the East of England is seeking an experienced Ward Manager to lead a busy acute medical ward. NMC registration, proven ward leadership experience and strong patient flow management skills required.', company: 'RecX Direct Client', location: 'East of England, UK', workModel: 'onsite', industry: 'Healthcare & Nursing', seniorityLevel: 'senior', salaryMin: 44000, salaryMax: 56000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T11:00:00.000Z', splitAmount: 5500, splitCurrency: 'USD' },
{ id: 'r-125', source: 'xchange', title: 'Chief Revenue Officer', descriptionSnippet: 'A Series C SaaS business is seeking a CRO to unify sales, marketing and customer success under a single revenue strategy. Proven track record scaling ARR from $20M to $100M+ in a B2B SaaS environment required.', company: 'Xchange Partner', location: 'Remote (US)', workModel: 'remote', industry: 'Sales', seniorityLevel: 'executive', salaryMin: 250000, salaryMax: 350000, salaryCurrency: 'USD', roleType: 'permanent', postedAt: '2026-01-21T09:00:00.000Z', splitAmount: 35000, splitCurrency: 'USD' },
{ id: 'r-126', source: 'recx_direct', title: 'Mechanical Project Engineer', descriptionSnippet: 'A process engineering contractor in Aberdeen is seeking a Mechanical Project Engineer to manage the delivery of piping and pressure systems packages on oil and gas modification projects. P&IDs, HAZOP and ASME/PED knowledge required.', company: 'RecX Direct Client', location: 'Aberdeen, UK', workModel: 'hybrid', industry: 'Engineering & Manufacturing', seniorityLevel: 'mid', salaryMin: 50000, salaryMax: 68000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-03-13T12:00:00.000Z', splitAmount: 7000, splitCurrency: 'USD' },
{ id: 'r-127', source: 'xchange', title: 'Head of Compliance - Asset Management', descriptionSnippet: 'A boutique asset management firm in London is seeking a Head of Compliance to own the FCA regulatory framework, manage SMCR obligations and advise the board on all compliance matters. CF10/CF11 approved person status required.', company: 'Xchange Partner', location: 'London, UK', workModel: 'hybrid', industry: 'Legal', seniorityLevel: 'executive', salaryMin: 120000, salaryMax: 160000, salaryCurrency: 'GBP', roleType: 'permanent', postedAt: '2026-01-20T09:00:00.000Z', splitAmount: 18000, splitCurrency: 'GBP' },
];

// ─── BATCH 3b: Roles 107–127 — coming in next commit ─────────────────────────
const ROLES_BATCH_3B: Role[] = [];

export const ALL_DEMO_ROLES: Role[] = [
  ...ROLES_BATCH_1,
  ...ROLES_BATCH_2,
  ...ROLES_BATCH_3,
  ...ROLES_BATCH_3B,
];

export async function GET() {
  try {
    const response = await fetch('https://app.recxchange.io/api/public/roles', {
      headers: { 'x-api-key': 'apaintballgunthatshootssausages' },
      cache: 'no-store'
    });

    if (!response.ok) {
      return NextResponse.json({
        total: ALL_DEMO_ROLES.length,
        lastUpdated: new Date().toISOString(),
        roles: ALL_DEMO_ROLES,
        demo: true
      });
    }

    const data: APIResponse = await response.json();

    if (!data.roles || !Array.isArray(data.roles)) {
      return NextResponse.json({
        total: ALL_DEMO_ROLES.length,
        lastUpdated: new Date().toISOString(),
        roles: ALL_DEMO_ROLES,
        demo: true
      });
    }

    const filteredRoles = data.roles.filter(role => {
      if (role.source === 'recx_direct') return true;
      if (role.source === 'xchange' && role.splitAmount && role.splitCurrency) {
        return convertToUSD(role.splitAmount, role.splitCurrency) >= 1000;
      }
      return false;
    });

    return NextResponse.json({
      total: filteredRoles.length,
      lastUpdated: data.lastUpdated,
      roles: filteredRoles,
      demo: false
    });
  } catch (error) {
    console.error('Error fetching roles:', error);
    return NextResponse.json({
      total: ALL_DEMO_ROLES.length,
      lastUpdated: new Date().toISOString(),
      roles: ALL_DEMO_ROLES,
      demo: true
    });
  }
}
